### ISSUE TITLE
Only disassemble scanned bytes

### ISSUE THREAD

**Issue by nemerle** [uxmal/reko#31]
Currently disassembly view will try to display all bytes as instructions ( sometimes causing crashes ), maybe we could display all bytes as byte definition instructions until they are marked as code by the scanner ?

**Comment by uxmal** [comment]
We still want to display instructions for areas that the scanner can't reach, for instance because they are virtual functions or switch statements which couldn't be resolved by reko.

How about marking the instructions in some manner similar to the memory view, such that scanned instuctions will have the background color of code, while unscanned instructions remain white. 

If you are seeing a crash when disassembling, could you report what bytes are causing the crash? That is a bug and should be fixed.

**Comment by nemerle** [comment]
It's crashing after opening m68k BENCHFN and scrolling around ( basically the random bytes are interpreted as one of unimplemented 68020 instructions )

**Comment by uxmal** [comment]
If the binary is free to share (no copyright restrictions) could you create a folder ~/subjects/regressions/reko-31 and add it there for me to analyze?

**Comment by nemerle** [comment]
The binary is already a part of reko :smile: reko/src/UnitTests/arch/m68k/images/BENCHFN

**Comment by uxmal** [comment]
How embarrassing! Sorry, I'd forgotten about your binaries. I'm going to move them to ~/subjects/Hunk-m68k, so they're in a more logical location.

**Comment by uxmal** [comment]
Done. I will play around with this to see if I can trigger a crash. I know that the m68k disassembler is a little whiny when it can't properly decode an operand. It shouldn't crash, but instead mark the instruction as valid and advance 2 bytes to the next possible operation.

**Comment by uxmal** [comment]
@nemerle , try this again. You will still see `illegal` for invalid instructions, which I think is OK, but no more crashes. If you feel motivated, you could take a stab at implementing some of those 68020 instructions. If you do, I recommend using the unit test classes as examples.

**Comment by nemerle** [comment]
hmm.. i think those should actually return 'invalid' instruction if the cpu is set to 68000/68010 :smile:
I'll look into doing that

**Comment by uxmal** [comment]
Currently, reko doesn't distinguish between the different flavors of the m68k CPU. If you feel eager, you can implement a m68000 and a m68010 class. Do open a separate issue if you decide to do this; that way we can track it.

As far as this issue is concerned, do you think it can be closed?

**Comment by nemerle** [comment]
Yup, I think so, I still get exceptions, but now all of them are related to 68020 instructions
